language: python
python:
- 3.6
- 3.5
- 3.4
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: statik
  password:
    secure: iYqZbt7VZQl3wKtDFrnM0vYe7pQ6jjma+4aU4YdxEuXulfelwDh82nSlqvWhV7EJAFrbgBTXmEPSQsDlQ3ib+kQYo16miCAdcPhoCkH0zj/nfL48Dijq454uhAnO5tGHze4oMhjYMx6+RX4nuoNmoaSDGJXx+NRBV3cuvC1q6+TJwXb+EvhQP1vVpZdTqmsJQaGQsiYhAjutNW8BMxSa4RC9Cw0YZ1DLxCtcczaX9LMLAUjqCatQXH0ENq4PcwMEA26WAqWPQEUehvXpgr5bEJBkfnTb6kH/ifzDYR4R2gQ8krmOzIr3TQrgw5+cliDIvM4r8d0wNwAzpWTRuuOiZcKsKuD3Uo12hEdxpXVZch4Ct6e/fWFmKiVCLNFWgmNMWV3TqRqH+FC5ISuPrHedHTPIn0gxJlPTvOwfONtaqwVq2BzQHTA/XPZvPZ+sKHEOWlFhF70M4trwjv74mqzknbYF+msg2MoH+mmqde80pIKfZanmBn6NNhY7+32QNi0lpjLzfRa10tbd8PA1vAGXQ0bKZHH3+d5AERHHN8IVUEJpGWfyBYgURjXDj0SIHGOIHl5jhzJ2CG3CRGVyMgasxZdPJ/82TO4vcZcWQyxZ+UampOnrTCG9nPESSj9HKdYIUsdIf1b05Xx+mdKFjrmD+7gJbKtcq8vn87HFs3oTyA0=
  on:
    tags: true
    repo: kindlyops/risky
    python: 3.6
